# Generated by Django 3.0.3 on 2020-07-28 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendee',
            name='profile_pic',
        ),
    ]
