# Generated by Django 3.0.3 on 2020-07-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_attendee_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('Online Event', 'Online Event'), ('Physical Event', 'Physical Event')], default='Online Event', max_length=50),
        ),
    ]
