# Generated by Django 3.0.3 on 2020-07-29 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200729_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='OROcCNI', max_length=255, unique=True),
        ),
    ]
