# Generated by Django 3.0.3 on 2020-07-29 09:27

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200729_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.SlugField(default='wfmnqspq', max_length=255, unique=True),
        ),
    ]
