# Generated by Django 3.0.3 on 2020-07-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200729_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='attendee',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
