# Generated by Django 3.0.3 on 2020-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20201204_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
